# Generated by Django 2.0.5 on 2018-05-31 00:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_bloque', models.BooleanField()),
                ('comentario', models.TextField()),
                ('num_linea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=256)),
                ('whois', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32)),
                ('num_linea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ofuscacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_phishtank', models.BooleanField()),
                ('recurso', models.CharField(max_length=256)),
                ('separador', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=512)),
                ('captura', models.CharField(max_length=512)),
                ('whois', models.TextField()),
                ('nombre_archivo', models.CharField(max_length=256)),
                ('hash_archivo', models.CharField(max_length=32)),
                ('reportado', models.BooleanField()),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('entidades_afectadas', models.ManyToManyField(to='phishing.Entidades')),
                ('ofuscacion', models.ManyToManyField(to='phishing.Ofuscacion')),
            ],
        ),
        migrations.AddField(
            model_name='hash',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.Url'),
        ),
        migrations.AddField(
            model_name='correo',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.Url'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.Url'),
        ),
    ]
